### ISSUE TITLE
Webpack5 Support

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/webpack-dashboard#316]
Support webpack 5 and aggregate all other tickets here. 

## Status
WIP upstream branch for `inspectpack`: https://github.com/FormidableLabs/inspectpack/compare/chore/webpack5-02

## Tasks
- [x] Upgrade to new webpack5 compatible `inspectpack@4.6.0`
- [x] Upgrade dashboard test fixtures / everything to webpack5 and check everything out.
- [x] Webpack 5 warning message conflict #314
- [ ] webpack v5 with express: compiler.apply is not a function #312

**Comment by sourena2575** [comment]
Is there any progress on this is up or your still working on this?

**Comment by ryan-roemer** [comment]
Yes, as this ticket mentions in the statutes we’re working on inspectpack (the underlying engine of this dashboard first) and you can track progress here: https://github.com/FormidableLabs/inspectpack/issues/156

**Comment by ryan-roemer** [comment]
*Update*: Full webpack5 support `inspectpack` PR up at: https://github.com/FormidableLabs/inspectpack/pull/157

**Comment by ryan-roemer** [comment]
Update: Going to tackle #312 post-webpack5 support version release.
